services:
  backend:
    image: nightdev19/mysite-backend:latest
    container_name: mysite-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    image: nightdev19/mysite-frontend:latest
    container_name: mysite-frontend
    ports:
      - "80:80"

  mongodb:
    image: mongo:7.0.12
    container_name: mysite-mongodb
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./mongodb/.env

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mysite-mongo-express
    ports:
      - "8081:8081"
    env_file:
      - ./mongo-express/.env
    depends_on:
      - mongodb

volumes:
  mongodb_data:
